version: "3"
services:

  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file: 
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - 8080:8080
  
  server:
    depends_on:
      - db
    build:
      context: ./server 
      dockerfile: Dockerfile
    image: christopherkyle/capstone-server
    env_file: 
      - ./server/.env
    ports:
      - 3001:3001
    environment:
      DB_HOST: db
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      # - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    image: christopherkyle/capstone-client
    ports:
      - 3000:3000
    stdin_open: true
  
  nginx:
    depends_on:
      - server
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    image: christopherkyle/capstone-nginx
    ports:
      - "80:80"
